version: "3"
services:
  web:
    build: .
    container_name: pe-portfolio
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=portfolio
    depends_on:
      - db
    volumes:
      - .:/pe-portfolio

  db:
    image: mysql:5.7
    restart: always
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: portfolio
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

