name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ secrets.PROJECT_ROOT }}
            echo "Current directory: $(pwd)"
            echo "Listing files..."
            ls -la
            # === Your deploy commands go here ===
            # Example:
            # git pull --rebase
            # docker compose pull
            # docker compose up -d
