name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TESTING: "true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Setup Python Virtual environment
        run: |
          python -m venv python3-virtualenv
          python3-virtualenv/bin/python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then
            python3-virtualenv/bin/pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping."
          fi

      - name: Ensure test script is executable
        run: chmod +x ./run_test.sh

      - name: Run tests
        run: ./run_test.sh
